### PR TITLE
Losslessly optimize agent maps to shrink them by 7%

### PR DESCRIPTION
**Pull request by alibosworth**
#### Before

```
Clippy/map.png  1,458,395
Links/map.png     890,718
Merlin/map.png   110,5278
Rocky/map.png   1,340,942
Rover/map.png     732,085
Total           5,527,418
```
#### After

```
Clippy/map.png  1,333,530
Links/map.png     819,223
Merlin/map.png  1,037,168
Rocky/map.png   1,239,901
Rover/map.png     698,394
Total           5,128,216
```

### CODE REVIEW

**Comment by karlbright** [comment]
Every little bit helps.

**Comment by smore-inc** [comment]
What did you use for this btw?
Our pngs were the result of pngcrush -force -l 9 -brute :p

**Comment by keithamus** [comment]
The best compression tool for PNGs is [PNGOUT](http://advsys.net/ken/utils.htm). If you're on a Mac you can use [Brew](http://mxcl.github.com/homebrew/) to install it, and use [ImageOptim](http://imageoptim.com/) for a friendly UI. If you're on Windows, you can download the exe from the PNGOUT website, and use [PNGGauntlet](http://pnggauntlet.com/) as for a friendly UI. 

PNGOUT gets clippy down to 1,312,954 - an additional 1.5% reduction from this pull request. Haven't tried with the others - teach a man to fish etc.

**Comment by smore-inc** [comment]
Thanks :)

**Comment by alibosworth** [comment]
Yeah, I just ran these files these through ImageOptim with the default settings.

**Comment by keithamus** [comment]
The big caveat to ImageOptim is that it works best if you `brew install pngout` and make PNGOUT your default Screenshot of ImageOptim preferences with PNGOUT enabled

**Pull request merged**
